/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCiclosRouteImport } from './routes/_authenticated/ciclos'
import { Route as AuthenticatedCicloCicloIdIndexRouteImport } from './routes/_authenticated/ciclo.$cicloId.index'
import { Route as AuthenticatedCicloCicloIdDiagnosticoRouteImport } from './routes/_authenticated/ciclo.$cicloId.diagnostico'
import { Route as AuthenticatedCicloCicloIdEscolhasRouteImport } from './routes/_authenticated/ciclo.$cicloId.escolhas'
import { Route as AuthenticatedCicloCicloIdMapaRouteImport } from './routes/_authenticated/ciclo.$cicloId.mapa'
import { Route as AuthenticatedCicloCicloIdPainelRouteImport } from './routes/_authenticated/ciclo.$cicloId.painel'
import { Route as AuthenticatedCicloCicloIdPessoasRouteImport } from './routes/_authenticated/ciclo.$cicloId.pessoas'
import { Route as AuthenticatedCicloCicloIdIniciativaIniciativaIdRouteImport } from './routes/_authenticated/ciclo.$cicloId.iniciativa.$iniciativaId'
import { Route as AuthenticatedCicloCicloIdObjetivoObjetivoIdRouteImport } from './routes/_authenticated/ciclo.$cicloId.objetivo.$objetivoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCiclosRoute = AuthenticatedCiclosRouteImport.update({
  id: '/ciclos',
  path: '/ciclos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCicloCicloIdIndexRoute =
  AuthenticatedCicloCicloIdIndexRouteImport.update({
    id: '/ciclo/$cicloId/',
    path: '/ciclo/$cicloId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCicloCicloIdDiagnosticoRoute =
  AuthenticatedCicloCicloIdDiagnosticoRouteImport.update({
    id: '/ciclo/$cicloId/diagnostico',
    path: '/ciclo/$cicloId/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCicloCicloIdEscolhasRoute =
  AuthenticatedCicloCicloIdEscolhasRouteImport.update({
    id: '/ciclo/$cicloId/escolhas',
    path: '/ciclo/$cicloId/escolhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCicloCicloIdMapaRoute =
  AuthenticatedCicloCicloIdMapaRouteImport.update({
    id: '/ciclo/$cicloId/mapa',
    path: '/ciclo/$cicloId/mapa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCicloCicloIdPainelRoute =
  AuthenticatedCicloCicloIdPainelRouteImport.update({
    id: '/ciclo/$cicloId/painel',
    path: '/ciclo/$cicloId/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCicloCicloIdPessoasRoute =
  AuthenticatedCicloCicloIdPessoasRouteImport.update({
    id: '/ciclo/$cicloId/pessoas',
    path: '/ciclo/$cicloId/pessoas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute =
  AuthenticatedCicloCicloIdIniciativaIniciativaIdRouteImport.update({
    id: '/ciclo/$cicloId/iniciativa/$iniciativaId',
    path: '/ciclo/$cicloId/iniciativa/$iniciativaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute =
  AuthenticatedCicloCicloIdObjetivoObjetivoIdRouteImport.update({
    id: '/ciclo/$cicloId/objetivo/$objetivoId',
    path: '/ciclo/$cicloId/objetivo/$objetivoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ciclos': typeof AuthenticatedCiclosRoute
  '/ciclo/$cicloId/diagnostico': typeof AuthenticatedCicloCicloIdDiagnosticoRoute
  '/ciclo/$cicloId/escolhas': typeof AuthenticatedCicloCicloIdEscolhasRoute
  '/ciclo/$cicloId/mapa': typeof AuthenticatedCicloCicloIdMapaRoute
  '/ciclo/$cicloId/painel': typeof AuthenticatedCicloCicloIdPainelRoute
  '/ciclo/$cicloId/pessoas': typeof AuthenticatedCicloCicloIdPessoasRoute
  '/ciclo/$cicloId/': typeof AuthenticatedCicloCicloIdIndexRoute
  '/ciclo/$cicloId/iniciativa/$iniciativaId': typeof AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute
  '/ciclo/$cicloId/objetivo/$objetivoId': typeof AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ciclos': typeof AuthenticatedCiclosRoute
  '/ciclo/$cicloId/diagnostico': typeof AuthenticatedCicloCicloIdDiagnosticoRoute
  '/ciclo/$cicloId/escolhas': typeof AuthenticatedCicloCicloIdEscolhasRoute
  '/ciclo/$cicloId/mapa': typeof AuthenticatedCicloCicloIdMapaRoute
  '/ciclo/$cicloId/painel': typeof AuthenticatedCicloCicloIdPainelRoute
  '/ciclo/$cicloId/pessoas': typeof AuthenticatedCicloCicloIdPessoasRoute
  '/ciclo/$cicloId': typeof AuthenticatedCicloCicloIdIndexRoute
  '/ciclo/$cicloId/iniciativa/$iniciativaId': typeof AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute
  '/ciclo/$cicloId/objetivo/$objetivoId': typeof AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ciclos': typeof AuthenticatedCiclosRoute
  '/_authenticated/ciclo/$cicloId/diagnostico': typeof AuthenticatedCicloCicloIdDiagnosticoRoute
  '/_authenticated/ciclo/$cicloId/escolhas': typeof AuthenticatedCicloCicloIdEscolhasRoute
  '/_authenticated/ciclo/$cicloId/mapa': typeof AuthenticatedCicloCicloIdMapaRoute
  '/_authenticated/ciclo/$cicloId/painel': typeof AuthenticatedCicloCicloIdPainelRoute
  '/_authenticated/ciclo/$cicloId/pessoas': typeof AuthenticatedCicloCicloIdPessoasRoute
  '/_authenticated/ciclo/$cicloId/': typeof AuthenticatedCicloCicloIdIndexRoute
  '/_authenticated/ciclo/$cicloId/iniciativa/$iniciativaId': typeof AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute
  '/_authenticated/ciclo/$cicloId/objetivo/$objetivoId': typeof AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ciclos'
    | '/ciclo/$cicloId/diagnostico'
    | '/ciclo/$cicloId/escolhas'
    | '/ciclo/$cicloId/mapa'
    | '/ciclo/$cicloId/painel'
    | '/ciclo/$cicloId/pessoas'
    | '/ciclo/$cicloId/'
    | '/ciclo/$cicloId/iniciativa/$iniciativaId'
    | '/ciclo/$cicloId/objetivo/$objetivoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ciclos'
    | '/ciclo/$cicloId/diagnostico'
    | '/ciclo/$cicloId/escolhas'
    | '/ciclo/$cicloId/mapa'
    | '/ciclo/$cicloId/painel'
    | '/ciclo/$cicloId/pessoas'
    | '/ciclo/$cicloId'
    | '/ciclo/$cicloId/iniciativa/$iniciativaId'
    | '/ciclo/$cicloId/objetivo/$objetivoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ciclos'
    | '/_authenticated/ciclo/$cicloId/diagnostico'
    | '/_authenticated/ciclo/$cicloId/escolhas'
    | '/_authenticated/ciclo/$cicloId/mapa'
    | '/_authenticated/ciclo/$cicloId/painel'
    | '/_authenticated/ciclo/$cicloId/pessoas'
    | '/_authenticated/ciclo/$cicloId/'
    | '/_authenticated/ciclo/$cicloId/iniciativa/$iniciativaId'
    | '/_authenticated/ciclo/$cicloId/objetivo/$objetivoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ciclos': {
      id: '/_authenticated/ciclos'
      path: '/ciclos'
      fullPath: '/ciclos'
      preLoaderRoute: typeof AuthenticatedCiclosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/': {
      id: '/_authenticated/ciclo/$cicloId/'
      path: '/ciclo/$cicloId'
      fullPath: '/ciclo/$cicloId/'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/diagnostico': {
      id: '/_authenticated/ciclo/$cicloId/diagnostico'
      path: '/ciclo/$cicloId/diagnostico'
      fullPath: '/ciclo/$cicloId/diagnostico'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/escolhas': {
      id: '/_authenticated/ciclo/$cicloId/escolhas'
      path: '/ciclo/$cicloId/escolhas'
      fullPath: '/ciclo/$cicloId/escolhas'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdEscolhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/mapa': {
      id: '/_authenticated/ciclo/$cicloId/mapa'
      path: '/ciclo/$cicloId/mapa'
      fullPath: '/ciclo/$cicloId/mapa'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/painel': {
      id: '/_authenticated/ciclo/$cicloId/painel'
      path: '/ciclo/$cicloId/painel'
      fullPath: '/ciclo/$cicloId/painel'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/pessoas': {
      id: '/_authenticated/ciclo/$cicloId/pessoas'
      path: '/ciclo/$cicloId/pessoas'
      fullPath: '/ciclo/$cicloId/pessoas'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdPessoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/iniciativa/$iniciativaId': {
      id: '/_authenticated/ciclo/$cicloId/iniciativa/$iniciativaId'
      path: '/ciclo/$cicloId/iniciativa/$iniciativaId'
      fullPath: '/ciclo/$cicloId/iniciativa/$iniciativaId'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdIniciativaIniciativaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo/$cicloId/objetivo/$objetivoId': {
      id: '/_authenticated/ciclo/$cicloId/objetivo/$objetivoId'
      path: '/ciclo/$cicloId/objetivo/$objetivoId'
      fullPath: '/ciclo/$cicloId/objetivo/$objetivoId'
      preLoaderRoute: typeof AuthenticatedCicloCicloIdObjetivoObjetivoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCiclosRoute: typeof AuthenticatedCiclosRoute
  AuthenticatedCicloCicloIdDiagnosticoRoute: typeof AuthenticatedCicloCicloIdDiagnosticoRoute
  AuthenticatedCicloCicloIdEscolhasRoute: typeof AuthenticatedCicloCicloIdEscolhasRoute
  AuthenticatedCicloCicloIdMapaRoute: typeof AuthenticatedCicloCicloIdMapaRoute
  AuthenticatedCicloCicloIdPainelRoute: typeof AuthenticatedCicloCicloIdPainelRoute
  AuthenticatedCicloCicloIdPessoasRoute: typeof AuthenticatedCicloCicloIdPessoasRoute
  AuthenticatedCicloCicloIdIndexRoute: typeof AuthenticatedCicloCicloIdIndexRoute
  AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute: typeof AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute
  AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute: typeof AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCiclosRoute: AuthenticatedCiclosRoute,
  AuthenticatedCicloCicloIdDiagnosticoRoute:
    AuthenticatedCicloCicloIdDiagnosticoRoute,
  AuthenticatedCicloCicloIdEscolhasRoute:
    AuthenticatedCicloCicloIdEscolhasRoute,
  AuthenticatedCicloCicloIdMapaRoute: AuthenticatedCicloCicloIdMapaRoute,
  AuthenticatedCicloCicloIdPainelRoute: AuthenticatedCicloCicloIdPainelRoute,
  AuthenticatedCicloCicloIdPessoasRoute: AuthenticatedCicloCicloIdPessoasRoute,
  AuthenticatedCicloCicloIdIndexRoute: AuthenticatedCicloCicloIdIndexRoute,
  AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute:
    AuthenticatedCicloCicloIdIniciativaIniciativaIdRoute,
  AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute:
    AuthenticatedCicloCicloIdObjetivoObjetivoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
